apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-ddd
  annotations:
    github.com/project-slug: carlangas159/backstage-ddd
spec:
  type: other
  lifecycle: unknown
  targets:
    - ./laravel-12-ddd-standard/catalog-info.yaml
